### ISSUE TITLE
PatterView has to ignore swipes of parent

### ISSUE THREAD

**Issue by ghost** [DreaminginCodeZH/PatternLock#11]
Hi,

I had the PatternView in a Fragment in a ViewPager, the problem was when I started the Pattern the ViewPager was recognizing it as a swipe and thus swiping the pages.

I solved this with:

`onTouchEvent()`

`ViewParent parent = getParent();`
`parent.requestDisallowInterceptTouchEvent(true);`
`handleActionMove(event);`
`return true;`

Maybe it would be a nice idea to add an attribute in PatternView to ignoreParentSwipe or something and doing this.

**Comment by zhanghai** [comment]
Dealing with nested scrolling correctly in PatternView requires additional logic other than simply calling `requestDisallowInterceptTouchEvent()`, such as checking if itself is inside a scrollable container, and if so track the touch events, record the down x/y and take over the drag only if it is over the touch slop - as done in [`AbsSeekBar`](https://github.com/android/platform_frameworks_base/blob/87e1938be8e6c2ac7e6163a63df5dd69633cc836/core/java/android/widget/AbsSeekBar.java#L564). Since it is kind of complex, I'm not going to add such an implementation to the framework `LockPatternView`.
