### ISSUE TITLE
Russian language

### ISSUE THREAD

**Issue by kanphis** [DreaminginCodeZH/PatternLock#13]
Please, add russian translation for the library!
[values-ru.zip](https://github.com/DreaminginCodeZH/PatternLock/files/406527/values-ru.zip)
This is russian translation for library. I hope you'll add it and release update for your library
Thanks!

**Comment by jasoncheng911** [comment]
@kanphis russian.... awesome!.lol!!!

**Comment by zhanghai** [comment]
I'm not merging this PR because I'm unable to verify the translation; The official translation of `LockPatternView` related string resources can be found in the AOSP `platform_framework_base` repo, so translations for this library should be taken from there.

People who still want to use this translation can drop the file into their own `res` directory which will also override the string resources correctly.
